### ISSUE TITLE
extended template override don't work

### ISSUE THREAD

**Issue by proweb** [construct-framework/bootstruct#28]
Joomla 3.3.6
PHP 5.5
I'm trying to make template override for Joomla Article.
So as you write in template description:
_For example, to create an extended template override for article 37, add your new layout named article-37.php to /layouts/article_
I create article.php in /layouts/article folder and paste to it simple html markup, and it override ALL pages on my site, not only then view=article
So, why is that?

**Comment by betweenbrain** [comment]
Thanks for the report. It looks like you have identified a bug in the logic of how these are loaded (https://github.com/construct-framework/bootstruct/blob/develop/elements/logic.php#L353-L385). I see that the view is checked for `category` and 'categories`, but not`article`. I have just pushed a fix to https://github.com/construct-framework/bootstruct/tree/issue-28, can you test?

**Comment by proweb** [comment]
Thanks, Thomas.
Now its work the right way

**Comment by betweenbrain** [comment]
Thanks for testing @proweb. This has been merged for the next release.
