### ISSUE TITLE
Installer fails for 3-0

### ISSUE THREAD

**Issue by Duke3D** [construct-framework/bootstruct#4]
Installer is attempting to locate the bootstrap.min.css files in the css directory but they are not present in the folder.  Is this because they are installed in media/jui by Joomla 3-0 and the manifest has not been updated to match?  

Same issue for the construct-dark & light css files

Just for kicks I unzipped the master branch and then unzipped the 3-0 branch over it to see if that would fill in the gaps on the missing files.  The install of the unedited 3-0 manifest was successful, of course I may have a bunch of 2.5 override files in a 3.0 installation - but we'll see how it goes.

**Comment by betweenbrain** [comment]
Thanks! This should be resolved.

Also, based your feedback and that of others, I will be moving the 3-0 branch to master.
